# Generated by Django 4.2.7 on 2023-11-26 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название цели')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('goal_type', models.CharField(choices=[('Трата', 'Spending'), ('Пополнение', 'Refill')], default='Трата', max_length=32, verbose_name='Тип операций цели')),
                ('start_date', models.DateField(default=datetime.datetime.today, verbose_name='Дата начала цели')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания цели')),
                ('value', models.FloatField(verbose_name='Значение цели')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
            },
        ),
    ]
