# Generated by Django 4.2.7 on 2023-11-26 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='operation_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата операции'),
        ),
    ]
